# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoilerPlateCode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoilerPlateCode
  pod 'FormTextField'
  pod 'DynamicButton', '~> 3.0.2'
  pod "EVSlidingTableViewCell"
end
